version: '3.8'
services:
  front-end:
    container_name: patient-injection-front-end
    build:
      context: .
    command: npm start
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3001'
